HOURS_PER_DAY = 24.

MINUTES_PER_HOUR = 60.
SECONDS_PER_MINUTE = 60.
SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR

MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY
SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY

DAYS_PER_YEAR = 365.
DAYS_PER_WEEK = 7.

HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK

WEEKDAYS_PER_WEEK = 5.
WEEKEND_DAYS_PER_WEEK = 2.

MONTHS_PER_YEAR = 12.
